[package]
name = "cached-nix-shell"
version = "0.1.4"
authors = ["Albert Safin <xzfcpw@gmail.com>"]
license = "Unlicense OR MIT"
edition = "2018"

[dependencies]
blake3 = "0.3.6"
bytelines = "2.2.2"
file-lock = "1.1.20"
itertools = "0.9.0"
lazy_static = "1.4.0"
nix = "0.18.0"
once_cell = "1.4.0"
regex = "1.4.1"
serde_json = "1.0.57"
tempfile = "3.1.0"
ufcs = "0.1.0"
xdg = "2.2.0"
